server:
  port: 8080

spring:
  application:
    name: family-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: family-auth
          uri: lb://family-auth
          predicates:
            - Path=/api/auth/**

        - id: family-finance
          uri: lb://family-finance
          predicates:
            - Path=/api/bills/**
            - Path=/api/budget/**
            - Path=/api/category/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'
